services:
  server:
    container_name: seau.server
    env_file:
      - .container.env
    build:
      context: .
      dockerfile: Dockerfile
    # command: sh -c "npm run migrate:dev"
    ports:
      - "5123:5123"
    depends_on:
      - db
  db:
    container_name: seau.db
    image: mysql:lts
    restart: always
    env_file:
      - .db.env
    volumes:
      - ${PWD}/storage/db:/var/lib/mysql:rw
      - "${PWD}/docker.dump.sql:/docker-entrypoint-initdb.d/start.sql"
    ports:
      - "3306:3306"